<a href="https://colab.research.google.com/github/HelleR0/Books-Python/blob/main/numbPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
list=[[1,2,3],[4,5,6],[7,8,9]]
matrix=np.array(list)

In [ ]:
np.arange(1,15)

In [ ]:
np.arange(18)

In [ ]:
np.arange(1,46,5)

In [15]:
np.zeros(5)

In [ ]:
np.zeros(5,int)

In [ ]:
np.zeros(2,5)

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10,int)

In [ ]:
np.zeros((2,10),int)

In [ ]:
np.ones((5,5),int)

In [ ]:
np.arange(1,64,5)

In [ ]:
np.linspace(0,1,5)

In [ ]:
np.linspace(0,20,8)

In [ ]:
np.eye(3)

In [ ]:
np.random.rand(4,7)

In [ ]:
np.random.randn(4,7)

In [35]:
np.random.randint(4,7)

5

In [ ]:
sample_array=np.arange(50)
sample_array

In [39]:
rand_array=np.random.randint(0,100,20)
rand_array

In [ ]:
sample_array.reshape(2,25)

In [39]:
rand_array.min()

In [ ]:
rand_array.argmin()

In [ ]:
a=np.eye(5)
a

In [ ]:
a.T

In [55]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
sample_array[3]

In [ ]:
sample_array[3:7]

In [ ]:
sample_array[1:4]=100
sample_array

In [ ]:
sample_array[:]=100
sample_array

In [ ]:
sample_array=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_array

In [ ]:
sample_array[0:2,2]

In [59]:
sample_array[2,:]

array([56, 76, 24,  7])

In [ ]:
sample_array[:,(3,2)]

In [ ]:
sample_array=np.arange(1,20)
sample_array

In [ ]:
np.exp(sample_array)

In [ ]:
np.square(sample_array)

In [ ]:
np.sqrt(sample_array)

In [ ]:
np.log(sample_array)

In [ ]:
np.min(sample_array)

In [ ]:
np.max(sample_array)

In [ ]:
np.argmax(sample_array)

In [ ]:
np.std(sample_array)

In [ ]:
np.var(sample_array)

In [ ]:
np.mean(sample_array)

In [ ]:
sample_array=np.random.randn(3,4)
sample_array

In [ ]:
np.round(sample_array,decimals=3)

In [ ]:
sports=np.array(['golf','cricket','football','cricket','baseball','golf','football'])
np.unique(sports)